content/urls.py
from django.conf.urls import patterns, url
from content import views


urlpatterns = patterns('',
	url(r'^$', views.index, name="index"),
	url(r'^home/', views.index, name="index"),
	url(r'^post/(?P<year>\d{4})/(?P<month>\d{2})/(?P<post_id>\d+)/(?P<permalink>[-\w]+)/$', views.get_post, name="post"),
	url(r'about/', views.about, name="about"),
	url(r'^category/$', views.get_category, name="category"),
)

urlpatterns += patterns('',
	url(r'^post/$', views.get_post_list, name="post_list"),
)

my_portfolio/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'my_portfolio.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/filebrowser/', include(site.get_urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('content.urls', namespace="content")),
)

urlpatterns += patterns('',
    url(r'^', include('pages.urls', namespace="pages")),
)

urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

if settings.DEBUG :
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

pages/urls.py
from django.conf.urls import patterns, url
from pages import views

urlpatterns = patterns('',
	# url(r'^(?P<url>.*/)$', views.page_index),
	url(r'^(?P<url>.*)/$', views.page, name="page"),
)

comments/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from content.models import Post

# Create your models here.

class Comment(MPTTModel):
	post = models.ForeignKey(Post, verbose_name="Post")
	content = models.TextField(verbose_name="Comment")
	parent = TreeForeignKey('self', null=True, blank=True)
	author = models.CharField(max_length=50, null=True, blank=True)
	date = models.DateField(auto_now=True)
	status = models.BooleanField(default=False, verbose_name="Published")

	def __unicode__(self):
		return self.author

	class MPTTMeta:
		order_insertion_by = ['date']

content/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from pages.models import Page
from django.core.urlresolvers import reverse

# Create your models here.
#

COMMENT_ALLOWED_STATUS = (
	('ALLOWED', 'Open for comments'),
	('DISABLED', 'Close comments for this post'),
)

class Tag(models.Model):
	name = models.CharField(max_length=100, verbose_name="Tag")

	def __unicode__(self):
		return self.name

class Category(models.Model):
	name = models.CharField(max_length=50, verbose_name="Categories")
	description = models.TextField()
	class Meta:
		verbose_name_plural = "Categories"

	def __unicode__(self):
		return self.name

class Post(models.Model):
	title = models.CharField(max_length=200, verbose_name="Title")
	permalink = models.SlugField(verbose_name="Post URL Link")
	content = models.TextField()
	author = models.ForeignKey(User, null=True, blank=True)
	pub_date = models.DateField(verbose_name="Date Published")
	modified_date = models.DateField(auto_now=True, verbose_name="Date Modified")
	tag = models.ManyToManyField(Tag, blank=True, verbose_name="Post Tag", help_text="Put multiple tag separated with commas Example: \'computer, news, blog\'")
	category = models.ManyToManyField(Category, blank=True, verbose_name="Category")
	pub_status = models.BooleanField(verbose_name="Published")
	comments_status = models.CharField(max_length=20, choices=COMMENT_ALLOWED_STATUS, verbose_name="Comments Status")
	comments_count = models.BigIntegerField(blank=True, null=True, verbose_name="Comments Count")

	def __unicode__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.id:
			if not self.permalink:
				self.permalink = slugify(self.title)
		super(Post, self).save(*args, **kwargs)

	def get_absolute_url(self):
		from content import views
		return reverse(views.single_post)

content/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from content.models import Post, Tag, Category
from my_portfolio.theme_manager import theme_resolver

# Create your views here.
#

def index(request):
	return render(request, theme_resolver('homepage.html'))

def get_post_list(request):
    try:
    	post_query = Post.objects.filter(pub_status=True)
        paginator = Paginator(post_query, 2)
        page = request.GET.get('page')
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)
    except Post.DoesNotExist:
    	raise Http404
    context = {'post': post_list}
    return render(request, theme_resolver('index.html'), context)

def get_post(request, year, month, post_id, permalink):
	post = Post.objects.get(id=post_id)
	context = {'post': post, 'document_title': post.title}
	return render(request, theme_resolver('single.html'), context)

def get_category(request):
	category = Category.objects.all()
	context = {'categories': category}
	return render(request, theme_resolver('index.html'), context)

def about(request):
    pass

content/templates/default/about.html
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<meta></meta>
	</head>
	<body>
	</body>
</html>

content/templates/default/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	{% block header %}
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="{% static 'content/css/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'content/css/font-awesome.min.css' %}">
		{% block title %}
			<title>None</title>
		{% endblock title %}
	{% endblock header%}
</head>
<body>
	{% block main %}
		<h1>Hello World</h1>
	{% endblock %}
	{% block footer %}
		{% include 'default/footer.html' %}
	{% endblock %}
</body>
</html>

content/templates/default/comment.html
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<meta></meta>
	</head>
	<body>
	</body>
</html>

content/templates/default/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<meta></meta>
	</head>
	<body>
	</body>
</html>

content/templates/default/flatpage.html
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<meta></meta>
	</head>
	<body>
	</body>
</html>

content/templates/default/footer.html
<div class="footer">
	<div class="copyright">
		<small>Copyright &copy; Andry Widya Putra UN on 2014</small>
	</div>
</div>

content/templates/default/frontpage.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Andre Widya Portfolio</title>
</head>
<body>

</body>
</html>

content/templates/default/header.html
<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<meta></meta>
	</head>
	<body>

content/templates/default/homepage-default.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<meta charset="UTF-8">
	<title>Andre Widya Putra</title>
	<link rel="stylesheet" type="text/css" href="{% static 'content/css/main.css' %}">
	<script type="text/javascript" src="{% static 'content/js/jquery.js' %}"></script>
</head>
<body>
	<div class="main_container">
		<h1>
			<span class="slabtext">slabText – a jQuery plugin</span>
			<span class="slabtext">for producing big, bold & responsive headlines responsive headlines responsive headlines</span>
		</h1>
	</div>

	<script type="text/javascript" src="{% static 'content/js/slabtext/jquery.slabtext.js' %}"></script>
	<script>

	    // Function to slabtext the H1 headings
	    function slabTextHeadlines() {
	        $("h1").slabText({
	            // Don't slabtext the headers if the viewport is under 380px
	            "viewportBreakpoint":400
	        });
	    };

	    // Called one second after the onload event for the demo (as I'm hacking the
	    // fontface load event a bit here)

	    // Please do not do this in a production environment - you should really use
	    // google WebFont loader events (or something similar) for better control
	    $(window).load(function() {
	        // So, to recap... don't actually do this, it's nasty!
	        setTimeout(slabTextHeadlines, 1000);
	    });

	</script>
</body>
</html>

content/templates/default/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta description="Portfolio site of Andry Widya Putra">
	<title>Andry Widya Putra</title>
	<link rel="stylesheet" type="text/css" href="{% static 'content/css/homepage.css' %}">
</head>
<body>
	<div class="head-page">
		<nav>
			<ul class="top-nav">
				<li><a href="{% url 'content:post_list' %}">Blog</a></li>
				<li><a href="{% url 'content:about' %}">About</a></li>
			</ul>
		</nav>
		<div class="content-wrapper">
			<div class="image-wrapper">
				<img src="{% static 'content/img/author.jpg' %}" class="author-image">
			</div>
			<h1 class="author-name">Andry Widya Putra</h1>
			<h2 class="author-desc">Web Developer & Design</h2>
			<a href="#" class="button">Kick It</a>
		</div>
	</div>
</body>
</html>

content/templates/default/index.html
{% extends "default/base.html" %}
{% block title %}
	<title>{{ document_title }}</title>
{% endblock %}

{% block main %}
{% load menu_tags %}
	<div class="topmenu">
		<div class="wrapper">
			<ul class="menu">
				{% main_menu %}
			</ul>
		</div>
	</div>

	<div class="main_container" >
		{% if post %}
			<div class="content_wrapper">
				<section>
					{% for entry in post %}
						<div class="article_content">
							<header>
								<div class="title_wrapper">
									<h2 class="post_title"><a href="{% url 'content:post' entry.pub_date|date:'Y' entry.pub_date|date:'m' entry.id entry.permalink %}">{{ entry.title }}</a></h2>
									<ul class="no_bullet inline">
										<li><small><i class="fa fa-pencil"></i> {{ entry.author.get_full_name }} </small></li>
										<li><small><i class="fa fa-calendar"></i> {{ entry.pub_date|date:'F' }}, {{ entry.pub_date|date:'Y' }}</small></li>
									</ul>
								</div>
							</header>
							<article>
								<p>{{ entry.content|safe|truncatewords_html:85 }}</p>
								<p><a href="{% url 'content:post' entry.pub_date|date:'Y' entry.pub_date|date:'m' entry.id entry.permalink %}" >Read More <i class="fa fa-share"></i></a></p>
							</article>
						</div>
					{% endfor %}
				<section>
				<section>
					<div class="paginator">
						<span>
							{% if post.has_previous %}
								<a href="?page={{ post.previous_page_number }}">Previous</a>
							{% endif %}
							<span>
								Page {{ post.number }} of {{ post.paginator.num_pages }}
							</span>
							{% if post.has_next %}
								<a href="?page={{ post.next_page_number }}">Next</a>
							{% endif %}
						</span>
					</div>
				</section>
			</div>
		{% endif %}
	</div>
{% endblock main %}

content/templates/default/single.html
{% extends "default/base.html" %}
{% block title %}
	<title>{{ document_title }}</title>
{% endblock %}

{% block main %}

	{% load menu_tags %}
	<div class="topmenu">
		<div class="wrapper">
			<ul class="menu">
				{% main_menu %}
			</ul>
		</div>
	</div>
	{% if post %}
	<div class="fullpage_container">
		<div class="single_post_title_container">
			<div class="post_title_wrapper">
				<h2 class="post_title">{{ post.title }}</h2>
				<ul class="no_bullet inline">
					<li><small><i class="fa fa-pencil"></i> {{ post.author.get_full_name }} </small></li>
					<li><small><i class="fa fa-calendar"></i> {{ post.pub_date|date:'F' }}, {{ post.pub_date|date:'Y' }}</small></li>
				</ul>
			</div>
		</div>

		<div class="main_container">
			<div class="content_wrapper">
				{{ post.content|safe }}
			</div>
		</div>
	</div>
	{% endif %}
{% endblock main %}